name: Deploy via Portainer Webhook

on:
  push:
    branches:
      - main

jobs:
  trigger-portainer:
    runs-on: ubuntu-latest
    steps:
      - name: Call Portainer webhook
        run: |
          curl -sS -X POST "${{ secrets.PORTAINER_WEBHOOK_URL }}" -o /dev/null -w "%{http_code}\n"
